/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    if (args.length == 0) {
      System.out.println("usage: java -jar app.jar <name>");
    } else {
      System.out.println("Hello " + args[0] + "!");
    }
  }
}
